basePath: /api/v1
definitions:
  models.DbTest:
    properties:
      status:
        type: string
    type: object
  models.Pong:
    properties:
      status:
        type: string
    type: object
  models.SubjectContent:
    properties:
      subjectContent:
        type: string
      subjectContentId:
        type: string
      subjectId:
        type: string
    type: object
  models.Subjects:
    properties:
      keyStage:
        type: integer
      purposeOfStudy:
        type: string
      subject:
        type: string
      subjectId:
        type: string
    type: object
info:
  contact: {}
  title: curriculum-api
  version: "1.0"
paths:
  /db:
    get:
      description: Responds with fail or connected status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DbTest'
      summary: Basic health check to ensure the service can connect to the db
      tags:
      - DbTest
  /getSubjectContent:
    get:
      description: Responds with the all subject contents
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.SubjectContent'
            type: array
      summary: Get Subject Contents
      tags:
      - getSubjectContent
  /getSubjects:
    get:
      description: Responds with all subjects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Subjects'
            type: array
      summary: Get all subjects
      tags:
      - getSubjects
  /ping:
    get:
      description: Responds with pong status.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Pong'
      summary: Basic health check to ensure service is responding
      tags:
      - health
swagger: "2.0"
