definitions:
  models.Pong:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
  title: curriculum-api
  version: "1.0"
paths:
  /ping:
    get:
      description: Responds with pong status.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Pong'
            type: array
      summary: Basic health check to ensure service is respnding
      tags:
      - hralth
swagger: "2.0"
