basePath: /api/v1
definitions:
  models.Pong:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
  title: curriculum-api
  version: "1.0"
paths:
  /getSubjects:
    get:
      description: Responds with pong status.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Pong'
      summary: Basic health check to ensure service is responding
      tags:
      - getSubjects
  /ping:
    get:
      description: Responds with pong status.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Pong'
      summary: Basic health check to ensure service is responding
      tags:
      - health
swagger: "2.0"
